import faiss
import numpy as np
import bm25s

def build_search_indices(parent_asins: list[str], product_texts: list[str], embeddings_path: str):
    """
    Builds the Sparse (BM25S) and Dense (FAISS HNSW) indexes in memory.
    
    Args:
        parent_asins: List of ASIN strings (e.g. ["B0001...", "B0002..."]).
        product_texts: List of concatenated strings ("Title: ... Features: ...").
        embeddings_path: Filepath to the .npy file generated by the ML Engineer.
    """
    print(f"Building indices for {len(parent_asins)} products...")

    # 1. SPARSE INDEX (BM25S)
    # Tokenize the product texts (removes stopwords, standardizes text)
    corpus_tokens = bm25s.tokenize(product_texts, stopwords="en")
    
    # Initialize the BM25 model
    sparse_retriever = bm25s.BM25()
    
    # Build the inverted index in memory
    sparse_retriever.index(corpus_tokens)
    print("Sparse index (BM25S) built successfully.")

    # 2. DENSE INDEX (FAISS HNSW)
    # Load the 768-dimensional BLaIR embeddings (ensure they are float32 for FAISS)
    embeddings = np.load(embeddings_path).astype(np.float32)
    dim = embeddings.shape[1] 
    
    # Initialize the HNSW graph using Inner Product
    # Note: Inner Product + L2 Normalization = Cosine Similarity
    dense_index = faiss.IndexHNSWFlat(dim, 16, faiss.METRIC_INNER_PRODUCT) 
    
    # Set the ef_construction parameter for index building as specified in the plan
    dense_index.hnsw.efConstruction = 200 
    
    # Normalize the vectors in-place so Inner Product behaves like Cosine Similarity
    faiss.normalize_L2(embeddings)
    
    # Add the vectors to the graph to build it
    dense_index.add(embeddings)
    print("Dense index (FAISS HNSW) built successfully.")

    return sparse_retriever, dense_index
